I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 162, in script
    $ renpy.call(play_video)
  File "game/script.rpy", line 162, in <module>
    $ renpy.call(play_video)
NameError: name 'play_video' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 162, in script
    $ renpy.call(play_video)
  File "/Users/ishaaulakh/Documents/Documents - Isha’s MacBook Air/renpy-7.4.8-sdk/renpy/ast.py", line 923, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/ishaaulakh/Documents/Documents - Isha’s MacBook Air/renpy-7.4.8-sdk/renpy/python.py", line 2235, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 162, in <module>
    $ renpy.call(play_video)
NameError: name 'play_video' is not defined

Darwin-23.1.0-x86_64-i386-64bit
Ren'Py 7.4.8.1895
Calm Academy Beta
Sat Jan  6 17:05:40 2024
